//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OrderItem
    {
        public int order_num { get; set; }
        public int order_item { get; set; }
        public string prod_id { get; set; }
        public int quantity { get; set; }
        public decimal item_price { get; set; }

        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public decimal sum_item { get => quantity * Product.prod_price; }
    
        
    }
}
